/// Flutter icons Iwfpapp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Iwfpapp
///      fonts:
///       - asset: fonts/Iwfpapp.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class Iwfpapp {
  Iwfpapp._();

  static const _kFontFam = 'Iwfpapp';
  static const _kFontPkg = null;

  static const IconData fiber_new =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bug =
      IconData(0xf188, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData free_code_camp =
      IconData(0xf2c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mark_github =
      IconData(0xf308, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_commit =
      IconData(0xf315, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_branch =
      IconData(0xf346, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_merge =
      IconData(0xf3b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_pull_request =
      IconData(0xf3b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_compare =
      IconData(0xf3bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop_code =
      IconData(0xf5fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
