subprojects:
  - id: "repository infra"
    paths:
      - ".github/code-health__*"
    checks:
      - "code-health__generic"
  - id: "server infra"
    paths:
      - ".github/server__*"
      - ".github/release__*"
    checks:
      - "server__unit-test"
      - "server__build-test__docs"
      - "release__compatibility-test__app-server"
      - "release__server-emulator-image"
  - id: "app infra"
    paths:
      - ".github/app__*"
      - ".github/release__*"
      - "scripts/configure_flutter.sh"
    checks:
      - "app__build-test__web-catalog"
      - "app__build-test__web"
      - "app__build-test__docs"
      - "app__build-test__android"
      - "app__build-test__ios"
      - "app__build-test__macos"
      - "app__unit-test"
      - "app__integration-test__ipad"
      - "app__integration-test__iphone"
      - "app__integration-test__android"
      - "release__compatibility-test__app-server"
  - id: "client application"
    paths:
      - "app/**"
    checks:
      - "app__build-test__web-catalog"
      - "app__build-test__web"
      - "app__build-test__docs"
      - "app__build-test__android"
      - "app__build-test__ios"
      - "app__build-test__macos"
      - "app__unit-test"
      - "app__integration-test__ipad"
      - "app__integration-test__iphone"
      - "app__integration-test__android"
      - "release__compatibility-test__app-server"
  - id: "server"
    paths:
      - "functions/**"
    checks:
      - "server__unit-test"
      - "server__build-test__docs"
      - "release__compatibility-test__app-server"
      - "release__server-emulator-image"
