# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "submit to internal track in Google Play Store"
  lane :internal do
    begin
      gradle(task: 'bundle', build_type: 'Release')
      upload_to_play_store(
        track: 'internal',
        aab: '../build/app/outputs/bundle/release/app.aab',
        skip_upload_changelogs: true,
        skip_upload_screenshots: true,
        skip_upload_images: true
      )
    rescue => exception
      raise exception unless exception.message.include?('APK specifies a version code that has already been used.')
      puts 'Current version already present on the Play Store. Omitting this upload.'
    end
  end
end
