fastlane_version "2.28.3"

default_platform :android

platform :android do  
  desc "Submit to internal track in Google Play Store"
  lane :internal do
    begin
      gradle(task: 'bundle', build_type: 'Release')
      upload_to_play_store(
        track: 'internal',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_apk: true,
        skip_upload_changelogs: true,
        skip_upload_screenshots: true,
        skip_upload_images: true
      )
    rescue => exception
      raise exception unless exception.message.include?('apkNotificationMessageKeyUpgradeVersionConflict')
      puts 'Current version already present on the Play Store. Omitting this upload.'
    end
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    puts 'Not implemented'
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    puts 'Not implemented'
  end
end
