fastlane_version "2.28.3"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    puts 'Flutter testing is not supported yet, omit testing.'
  end
  
  desc "Submit to internal track in Google Play Store"
  lane :internal do
    begin
      gradle(task: 'bundle', build_type: 'Release')
      upload_to_play_store(
        track: 'internal',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_screenshots: true,
        skip_upload_images: true
      )
    rescue => exception
      raise exception unless exception.message.include?('apkNotificationMessageKeyUpgradeVersionConflict')
      puts 'Current version already present on the Play Store. Omitting this upload.'
    end
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    puts 'Not implemented'
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    puts 'Not implemented'
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
    puts 'Not implemented'
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
    puts 'Not implemented'
  end
end
