name: App Unit Test
on:
  push:
    branches:
      - "actions/app__unit-test__*"
  pull_request:
    branches:
      - "master"
    paths:
      - ".github/workflows/app__unit-test.yml"
      - ".github/checkgroup.yml"
      - "configs/actions.json"
      - "scripts/bash/configure_flutter.sh"
      - "scripts/bash/initialize_environment.sh"
      - "app/**"
  schedule:
    - cron: 0 2 * * *
jobs:
  app__unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Monorepo-Actions/config-for-actions@main
        id: get_action_configs
        with:
          config_files: ./configs/actions.json
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_action_configs.outputs.flutter_version }}
          channel: ${{ steps.get_action_configs.outputs.flutter_channel }}
      - name: configure Flutter and
        working-directory: ./scripts/bash
        run: source ./initialize_environment.sh && ./configure_flutter.sh && ./run_app_unit_tests.sh
