name: App Build Test (Web)
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "app/pubspec.yaml"
      - ".github/workflows/app__build-test__web.yml"
      - ".github/checkgroup.yml"
      - "scripts/configure_flutter.sh"
  schedule:
    - cron: 0 2 * * *
jobs:
  app__build-test__web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Monorepo-Actions/config-for-actions@main
        id: get_action_configs
        with:
          config_files: ./configs/actions.json
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_action_configs.outputs.flutter_version }}
          channel: ${{ steps.get_action_configs.outputs.flutter_channel }}
      - name: configure Flutter
        working-directory: ./scripts/bash
        run: source ./initialize_environment.sh && ./configure_flutter.sh
      - name: build web
        working-directory: ./app
        run: flutter build web
