name: App Integration Test (iPad)
on:
  push:
    branches:
      - "actions/app__integration-test__ipad__*"
  schedule:
    - cron: 0 2 * * *
jobs:
  app__integration-test__ipad:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Monorepo-Actions/config-for-actions@main
        id: get_action_configs
        with:
          config_files: ./configs/actions.json
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_action_configs.outputs.flutter_version }}
          channel: ${{ steps.get_action_configs.outputs.flutter_channel }}
      - name: start simulator
        working-directory: ./scripts/macos
        env:
          DEVICE_ID: ${{ steps.get_action_configs.outputs.ipad_device_id }}
        run: ./start_emulator.sh
      - name: configure Flutter
        working-directory: ./scripts/bash
        run: source ./initialize_environment.sh && ./configure_flutter.sh
      - name: run offline device end to end test
        working-directory: ./app
        run: flutter drive --target=test_driver/app.dart
      - name: upload online screenshot
        uses: actions/upload-artifact@master
        with:
          name: online_screenshot_ios
          path: /tmp/screenshots
