name: App Build Test (Android)
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "app/pubspec.yaml"
      - ".github/workflows/app__*"
      - "scripts/configure_flutter.sh"
      - ".github/checkgroup.yml"
  schedule:
    - cron: 0 2 * * *
jobs:
  app__build-test__android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Monorepo-Actions/config-for-actions@main
        id: get_action_configs
        with:
          config_files: ./configs/actions.json
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_action_configs.outputs.flutter_version }}
          channel: ${{ steps.get_action_configs.outputs.flutter_channel }}
      - name: upgrade Flutter
        working-directory: ./app
        run: |
          flutter channel master
          flutter upgrade
      - name: prepare credentials
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          source scripts/bash/initialize_environment.sh
          ./scripts/bash/fetch_android_credentials.sh
      - name: install dependencies
        working-directory: ./app
        run: flutter pub get
      - name: build app bundle
        working-directory: ./app
        run: flutter build appbundle
      - name: build apk package
        working-directory: ./app
        run: flutter build apk --split-per-abi
