name: App Integration Test (iPad)
on:
  pull_request:
    branches:
      - "master"
    paths:
      - ".github/checkgroup.yml"
      - ".github/workflows/app__integration-test__ipad.yml"
  push:
    branches:
      - "actions/app__integration-test__ipad__*"
  schedule:
    - cron: 0 2 * * *
jobs:
  app__integration-test__ipad:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Monorepo-Actions/config-for-actions@main
        id: get_action_configs
        with:
          config_files: ./configs/actions.json
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_action_configs.outputs.flutter_version }}
          channel: ${{ steps.get_action_configs.outputs.flutter_channel }}
      - name: "Configure Flutter, start iOS emulator and run integration tests (mock)"
        working-directory: ./scripts/bash
        env:
          DEVICE_ID: ${{ steps.get_action_configs.outputs.ipad_device_id }}
        run: |
          source ./initialize_environment.sh
          ./configure_flutter.sh
          ./app/test/emulator/ios.sh
          ./run_app_integration_test.sh
      - name: upload online screenshot
        uses: actions/upload-artifact@master
        with:
          name: online_screenshot_ios
          path: /tmp/screenshots
