name: App Unit Test
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "app/**"
      - "scripts/configure_flutter.sh"
      - ".github/workflows/app__*"
  schedule:
    - cron: 0 2 * * *
jobs:
  app__unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Monorepo-Actions/config-for-actions@main
        id: get_action_configs
        with:
          config_files: ./configs/actions.json
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_action_configs.outputs.flutter_version }}
          channel: ${{ steps.get_action_configs.outputs.flutter_channel }}
      - name: configure Flutter
        run: ./scripts/configure_flutter.sh
      - name: lint Dart code
        working-directory: ./app
        run: flutter analyze
      - name: run unit tests
        working-directory: ./app
        run: flutter test
