name: App Build Test (Web)
on:
  push:
    branches:
      - "actions/app__build-test__web__*"
  pull_request:
    branches:
      - "master"
    paths:
      - ".github/workflows/app__build-test__web.yml"
      - ".github/checkgroup.yml"
      - "configs/actions.json"
      - "scripts/configure_flutter.sh"
      - "scripts/bash/initialize_environment.sh"
      - "scripts/bash/build_app_web.sh"
      - "app/**"
  schedule:
    - cron: 0 2 * * *
jobs:
  app__build-test__web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Monorepo-Actions/config-for-actions@main
        id: get_action_configs
        with:
          config_files: ./configs/actions.json
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_action_configs.outputs.flutter_version }}
          channel: ${{ steps.get_action_configs.outputs.flutter_channel }}
      - name: "Configure Flutter and build web app"
        working-directory: ./scripts/bash
        run: |
          source ./initialize_environment.sh
          ./configure_flutter.sh
          ./build_app_web.sh
