name: App Build Test (Android)
on:
  push:
    branches:
      - "actions/app__build-test__android__*"
  schedule:
    - cron: 0 2 * * *
jobs:
  app__build-test__android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Monorepo-Actions/config-for-actions@main
        id: get_action_configs
        with:
          config_files: ./configs/actions.json
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_action_configs.outputs.flutter_version }}
          channel: ${{ steps.get_action_configs.outputs.flutter_channel }}
      - name: configure Flutter
        working-directory: ./scripts/bash
        run: source ./initialize_environment.sh && ./configure_flutter.sh
      - name: prepare credentials
        working-directory: ./scripts/bash
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: source ./initialize_environment.sh && ./fetch_android_credentials.sh
      - name: build Android package
        working-directory: ./scripts/bash
        run: source ./initialize_environment.sh && ./build_android_package.sh
