name: App Integration Test (Android)
on:
  pull_request:
    branches:
      - "master"
    paths:
      - ".github/checkgroup.yml"
      - ".github/workflows/app__integration-test__android.yml"
  push:
    branches:
      - "actions/app__integration-test__android__*"
  schedule:
    - cron: 0 2 * * *
jobs:
  app__integration-test__android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Monorepo-Actions/config-for-actions@main
        id: get_action_configs
        with:
          config_files: ./configs/actions.json
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_action_configs.outputs.flutter_version }}
          channel: ${{ steps.get_action_configs.outputs.flutter_channel }}
      - name: configure Flutter
        working-directory: ./scripts/bash
        run: source ./initialize_environment.sh && ./configure_flutter.sh
      - name: "Run Android integration test (mock)"
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2.11.1
        env:
          ANDROID_DEBUG: "true"
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          api-level: 28
          profile: "pixel_xl"
          script: cd ./scripts/bash && source ./initialize_environment.sh && ./run_android_integration_test.sh
