name: checkin generic
on:
  push:
    branches:
      - "master"
      - "dev/*"
      - "feature/*"
      - "release/*"
      - "fix/*"
      - "refactor/*"
      - "chore/*"
      - "actions/checkin-generic__*"
jobs:
  test:
    name: run generic tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.16.2"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.12.13+hotfix.9"
          channel: "stable"
      - name: install dependencies
        run: ./scripts/install_dependencies.sh
      - name: generic check
        run: ./scripts/lint_workspace.sh check
