name: checkin iwfpapp
on:
  push:
    branches:
      - "master"
      - "dev/*"
      - "feature/*"
      - "release/*"
    paths:
      - "iwfpapp/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - "master"
      - "dev/*"
      - "feature/*"
      - "release/*"
  schedule:
    - cron: 0 2 * * *
jobs:
  test:
    name: run iwfpapp checkin tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.2'
          channel: 'stable'
      - name: install iwfpapp flutter dependencies
        run: |
          cd ./iwfpapp
          flutter pub get
      - name: lint iwfpapp dart code
        run: |
          cd ./iwfpapp
          flutter analyze
      - name: run iwfpapp unit tests
        run: |
          cd ./iwfpapp
          flutter test
