name: checkin app
on:
  pull_request:
    branches:
      - "master"
  schedule:
    - cron: 0 2 * * *
  push:
    branches:
      - "master"
      - "dev/*"
      - "feature/*"
      - "release/*"
      - "fix/*"
      - "refactor/*"
      - "chore/*"
      - "actions/checkin-app__*"
    paths:
      - "app/*"
      - ".github/workflows/checkin_app.yml"
jobs:
  test:
    name: run app unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.16.2"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.20.2"
          channel: "stable"
      - name: upgrade Flutter
        if: matrix.os != 'windows-latest'
        working-directory: scripts/linux
        run: ./install_dependencies.sh
      - name: upgrade Flutter
        if: matrix.os == 'windows-latest'
        working-directory: scripts/windows
        run: ./install_dependencies.ps1
      - name: lint Dart code
        working-directory: app
        run: flutter analyze
      - name: run unit tests
        working-directory: app
        run: flutter test
