name: Generic Code Health Check
on:
  pull_request:
    branches:
      - "master"
  schedule:
    - cron: 0 2 * * *
jobs:
  code-health__generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Monorepo-Actions/config-for-actions@main
        id: get_action_configs
        with:
          config_files: ./configs/actions.json
      - uses: actions/setup-node@v1
        with:
          node-version: "12.16.2"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_action_configs.outputs.flutter_version }}
          channel: ${{ steps.get_action_configs.outputs.flutter_channel }}
      - name: run checks
        run: |
          source ./scripts/bash/initialize_environment.sh
          ./scripts/bash/install_dependencies.sh
          ./scripts/bash/lint_workspace.sh check
