name: Generic Code Health Check
on:
  push:
    branches:
      - "actions/code-health__generic__*"
  pull_request:
    branches:
      - "master"
  schedule:
    - cron: 0 2 * * *
jobs:
  code-health__generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Monorepo-Actions/config-for-actions@main
        id: get_action_configs
        with:
          config_files: ./configs/actions.json
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.get_action_configs.outputs.node_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_action_configs.outputs.flutter_version }}
          channel: ${{ steps.get_action_configs.outputs.flutter_channel }}
      - name: "Install dependencies and run code health check"
        working-directory: ./scripts/bash
        run: |
          source ./initialize_environment.sh
          ./install_dependencies.sh
          ./lint_workspace.sh check
