name: iwfpapp device test
on:
  push:
    branches:
      - "master"
      - "dev/*"
      - "feature/*"
      - "release/*"
      - "fix/*"
      - "refactor/*"
    paths:
      - "iwfpapp/**"
      - ".github/workflows/device_test_iwfpapp.yml"
  pull_request:
    branches:
      - "master"
  schedule:
    - cron: 0 2 * * *
jobs:
  ios_device_test:
    if: "github.event_name == 'schedule' || github.event_name == 'pull_request' || (github.event_name == 'push' && contains(github.event.head_commit.message, 'DEVICE_TEST'))"
    strategy:
      matrix:
        device:
          - "iPad Pro (12.9-inch) (3rd generation) (13.3)"
          - "iPhone 11 Pro Max (13.3)"
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'
      - name: install firebase cli
        run: npm install -g firebase-tools
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.5'
          channel: 'stable'
      - name: upgrade flutter
        run: |
          flutter channel master
          flutter upgrade
      - name: clean up workspace
        run: git clean -xffd
      - name: "List all simulators"
        run: "xcrun instruments -s"
      - name: start simulator
        run: |
          UDID=$(
            xcrun instruments -s |
            awk \
              -F ' *[][]' \
              -v 'device=${{ matrix.device }}' \
              '$1 == device { print $2 }'
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - name: install npm dependencies
        run: |
          cd ./iwfpapi/functions
          npm install
      - name: run offline device end to end test
        run: |
          cd ./iwfpapi/functions
          npm run device
      - name: upload offline screenshot
        uses: actions/upload-artifact@master
        with:
          name: offline_screenshot_${{ matrix.device }}
          path: /tmp/iwfpapp_screenshot
      - name: run online device end to end test
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          ./scripts/setenv.sh
          cd ./iwfpapp
          flutter pub get
          flutter test
          flutter drive --target=test_driver/app.dart
      - name: upload online screenshot
        uses: actions/upload-artifact@master
        with:
          name: online_screenshot_${{ matrix.device }}
          path: /tmp/iwfpapp_screenshot
