name: readable readme
on:
  schedule:
    - cron: "0 2,14 * * *"
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
jobs:
  lint-readme:
    name: lint readme files
    if: "github.event_name == 'schedule' || 
    (github.event_name == 'pull_request' || github.event_name == 'push') && contains(github.event.head_commit.message, 'LINT_README')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Readable Readme Lint
        uses: tianhaoz95/readable-readme@v1.0.4-beta
        env:
          RRLOG: "true"
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
