name: readable readme
on:
  schedule:
    - cron: "0 2,14 * * *"
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
jobs:
  lint-readme:
    name: Lint readme files
    runs-on: ubuntu-latest
    steps:
      - name: Readable Readme Lint
        uses: tianhaoz95/readable-readme@v1.0.3-beta
        env:
          RRLOG: "true"
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
