name: release-docs
on:
  push:
    branches: 
      - "master"
      - "actions/release-docs-*"
    paths:
      - "website/**"
      - "docs/**"
      - "iwfpapp/**"
      - ".github/workflows/**"
jobs:
  release-docs:
    name: generate documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.4'
          channel: 'stable'
      - name: upgrade flutter
        run: |
          flutter channel master
          flutter upgrade
      - name: install coverage visualization
        run: sudo apt install lcov
      - name: test iwfpapp with coverage
        run: |
          git clean -xffd
          cd ./iwfpapp
          flutter pub get
          flutter test --coverage
      - name: generate iwfpapp coverage report
        run: |
          cd ./iwfpapp
          genhtml coverage/lcov.info -o coverage
      - name: move iwfpapp coverage report to website
        run: |
          mkdir -p ./website/static/reports
          cp -r ./iwfpapp/coverage ./website/static/reports/iwfpapp_coverage_report
      - name: configure git credentials
        run: |
          git config --global user.email "tianhaoz@umich.edu"
          git config --global user.name "Tianhao Zhou"
      - name: deploy docs to GitHub pages
        run: |
          cd ./website
          echo "machine github.com login tianhaoz95 password $GITHUB_TOKEN" > ~/.netrc
          npm install
          npm run publish-gh-pages
        env:
          GIT_USER: ${{ secrets.DOCS_GIT_USER }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
