name: release-docs
on:
  push:
    branches: 
      - "master"
      - "actions/release-docs__*"
    paths:
      - "website/**"
      - "docs/**"
      - "iwfpapp/**"
      - ".github/workflows/release_docs.yml"
jobs:
  release-iwfpapp-api-doc:
    name: release iwfpapp api doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.5'
          channel: 'stable'
      - name: upgrade flutter
        run: |
          flutter channel master
          flutter upgrade
          flutter --version
      - name: install dartdoc
        run: |
          sudo apt-get update -y
          sudo apt-get install -y apt-transport-https
          sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
          sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
          sudo apt-get update
          sudo apt-get install dart
      - name: build docs
        run: |
          cd ./iwfpapp
          export PATH="$PATH:/usr/lib/dart/bin"
          flutter pub get
          dartdoc --exclude 'dart:async,dart:collection,dart:convert,dart:core,dart:developer,dart:io,dart:isolate,dart:math,dart:typed_data,dart:ui,dart:ffi,dart:html,dart:js,dart:js_util'
      - name: upload doc to repository
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          cd ./iwfpapp
          mkdir -p ~/upload
          cp -r doc/api ~/upload/docs
          cd ~/upload/docs
          git config --global user.email "tianhaoz@umich.edu"
          git config --global user.name "Tianhao Zhou"
          git init
          git add -A
          git commit -m "docs: update"
          git remote add origin https://github.com/iwfp/iwfpapp-doc.git
          echo "machine github.com login tianhaoz95 password $GITHUB_TOKEN" > ~/.netrc
          git push -u -f origin master
  release-iwfp-home:
    name: build iwfp home site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'
      - name: install yarn
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt update && sudo apt install yarn
      - name: build doc
        run: |
          cd ./iwfphome
          yarn
          yarn docz build
      - name: upload doc
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          cd ./iwfphome
          mkdir -p ~/upload
          cp -r .docz/dist ~/upload/docs
          cd ~/upload/docs
          git config --global user.email "tianhaoz@umich.edu"
          git config --global user.name "Tianhao Zhou"
          git init
          git add -A
          git commit -m "docs: update"
          git remote add origin https://github.com/iwfp/iwfp-home.git
          echo "machine github.com login tianhaoz95 password $GITHUB_TOKEN" > ~/.netrc
          git push -u -f origin master
  build-iwfpapi-api-doc:
    name: build iwfpapi API doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'
      - name: generate doc
        run: |
          cd ./iwfpapi/functions
          npm install
          npm run docs
      - name: upload doc to repository
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          cd ./iwfpapi/functions
          mkdir -p ~/upload
          cp -r docs ~/upload/docs
          cd ~/upload/docs
          touch .nojekyll
          git config --global user.email "tianhaoz@umich.edu"
          git config --global user.name "Tianhao Zhou"
          git init
          git add -A
          git commit -m "docs: update"
          git remote add origin https://github.com/iwfp/iwfpapi-doc.git
          echo "machine github.com login tianhaoz95 password $GITHUB_TOKEN" > ~/.netrc
          git push -u -f origin master
  release-iwfpapp-coverage-report:
    name: release iwfpapp coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.4'
          channel: 'stable'
      - name: upgrade flutter
        run: |
          flutter channel master
          flutter upgrade
      - name: install coverage visualization
        run: sudo apt install lcov
      - name: test iwfpapp with coverage
        run: |
          git clean -xffd
          cd ./iwfpapp
          flutter pub get
          flutter test --coverage
      - name: generate iwfpapp coverage report
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          cd ./iwfpapp
          genhtml coverage/lcov.info -o coverage
          mkdir -p ~/upload
          cp -r coverage ~/upload/docs
          cd ~/upload/docs
          touch .nojekyll
          git config --global user.email "tianhaoz@umich.edu"
          git config --global user.name "Tianhao Zhou"
          git init
          git add -A
          git commit -m "docs: update"
          git remote add origin https://github.com/iwfp/iwfpapp-coverage-report.git
          echo "machine github.com login tianhaoz95 password $GITHUB_TOKEN" > ~/.netrc
          git push -u -f origin master
  release-docs:
    name: generate documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.4'
          channel: 'stable'
      - name: upgrade flutter
        run: |
          flutter channel master
          flutter upgrade
      - name: install coverage visualization
        run: sudo apt install lcov
      - name: test iwfpapp with coverage
        run: |
          git clean -xffd
          cd ./iwfpapp
          flutter pub get
          flutter test --coverage
      - name: generate iwfpapp coverage report
        run: |
          cd ./iwfpapp
          genhtml coverage/lcov.info -o coverage
      - name: move iwfpapp coverage report to website
        run: |
          mkdir -p ./website/static/reports
          cp -r ./iwfpapp/coverage ./website/static/reports/iwfpapp_coverage_report
      - name: configure git credentials
        run: |
          git config --global user.email "tianhaoz@umich.edu"
          git config --global user.name "Tianhao Zhou"
      - name: deploy docs to GitHub pages
        run: |
          cd ./website
          echo "machine github.com login tianhaoz95 password $GITHUB_TOKEN" > ~/.netrc
          npm install
          npm run publish-gh-pages
        env:
          GIT_USER: ${{ secrets.DOCS_GIT_USER }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  