name: web release
on:
  push:
    branches:
      - "master"
      - "actions/release-web-app__*"
    paths:
      - "app/*"
      - ".github/workflows/release_web_app.yml"
jobs:
  release-web-app:
    name: release web app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.9'
          channel: 'stable'
      - name: install firebase cli
        run: npm install -g firebase-tools
      - name: switch to master channel
        run: flutter channel master
      - name: enable Flutter web
        run: flutter config --enable-web
      - name: install dependencies
        working-directory: ./app
        run: flutter pub get
      - name: build for web
        working-directory: ./app
        run: flutter build web
      - name: deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
        working-directory: ./app
        run: firebase deploy --only hosting:iwfpapp --token $FIREBASE_TOKEN
